version: "3"
services:
  mysql:
    container_name: quartz-schedule-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quartz_schedule_mysql
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
  redis:
    container_name: quartz-schedule-redis
    image: redis:latest
    ports:
      - 6379:6379